[context.production.environment]
HUGO_VERSION = "0.122.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404

[[redirects]]
  from = "/sdk/nodejs"
  to = "https://pinggy-io.github.io/sdk-nodejs/"
  status = 200

